### ISSUE TITLE
Edited Script Portion is removed

### ISSUE THREAD

**Issue by joncode21** [axoverse/xworld_amb#3]
1. When attempting to add new code in "XwNavAgent.cs" file  , it will revert back to original code state when the code file is saved and Unity 3D is played.

2. The red rectangles show the new codes added.

![3rd issue](https://user-images.githubusercontent.com/75573916/211751091-9717013e-8e6b-4815-871f-caafcb121f31.jpg)

**Comment by seghcder** [comment]
It may be because you are updating an imported package file. You can also only have one function named the same in a file. 

Suggest instead you create your own navmeshagent component eg RpNavMeshAgent.cs in Assets/Scripts directory, copy the contents from the xw file and then edit to your needs. Then attach to your agents and remove (or just disable) the xwnameshagent component.
